feat: use placeholder instead image
FilledStacks/session_mate pull request #11
Opened 2023-09-20 05:48 UTC by ferrarafer

- Replace real images with local placeholders
- Stall the app until session selected
- Improved data masking

NOTE: When I was wrapping the changes, I exceeded book api quota 😄 , I will double check all tomorrow, maybe will be better to avoid merge till tomorrow.

**DEMO**

https://github.com/FilledStacks/session_mate/assets/1505545/78886fd0-2083-4b7b-ba36-acf7e4531d35

https://github.com/FilledStacks/session_mate/assets/1505545/988934c8-cbd0-4b8f-897c-d0f046cbb516

2023-09-20 07:36 UTC, FilledStacks requested changes
This looks really great! I'm happy with it. 

One thing we need to do is to stall the app until we tap the play button, not until we select the session. 

Reason: we only need to fill the cache at that point since we might be tapping through different sessions before we select one to play.

2023-09-21 23:13 UTC, ferrarafer commented
**New Demo**

https://github.com/FilledStacks/session_mate/assets/1505545/9c8df236-e178-4ae3-9075-3b1f63abf72c

2023-09-22 07:10 UTC, FilledStacks approved these changes
Great PR! Local session replay is wrapped up nicely with these features.

2023-09-22 07:10 UTC, FilledStacks commented on example/lib/main.dart
> +        excludeKeysOnDataMasking: const [
Perfect

2023-09-22 07:10 UTC, FilledStacks commented on lib/src/widgets/driver_ui/driver_ui.dart
> +  const DriverUI({super.key, required this.child});
I'm very happy to see the required restart code removed

2023-09-22 07:10 UTC, FilledStacks commented on test/services/data_masking_service_test.dart
🔥

2023-09-22 07:10 UTC, FilledStacks commented on test/services/configuration_service_test.dart
🔥

2023-09-22 07:10 UTC, merged