feat: track current view
FilledStacks/session_mate pull request #14
Opened 2023-09-28 01:50 UTC by ferrarafer

Added `SessionMateNavigatorObserver` to track the current view during the recording of the session.

**NOTE**
Before merging this into main branch, you need to merge the following [PR](https://github.com/FilledStacks/session_mate/pull/13) into this branch.

2023-09-28 04:01 UTC, FilledStacks requested changes
Majority of the PR is good. I've left a few comments that we can chat about.

The biggest one is, I don't think the NavigatorObserver should be used by us through the package code. It mixes responsiiblities of being a class for the guest app and being a class for our package.

2023-09-28 04:01 UTC, FilledStacks commented on lib/src/app/locator_setup.dart
> +  locator.registerLazySingleton(() => SessionMateNavigatorObserver.instance);
Why is this registered here?

2023-09-28 04:01 UTC, FilledStacks commented on lib/src/http/event_tracker.dart
> +  final _routerObserver = locator<SessionMateNavigatorObserver>();
Responses don't need the view as they're not directly related. Meaning, we could be on a different view when a response comes back that was requested on the previous view. 

I mean, it might be useful, but right now I don't think we need it.

2023-09-28 04:01 UTC, FilledStacks commented on lib/src/widgets/interaction_recorder/interaction_recorder_viewmodel.dart
> +  final _routerObserver = locator<SessionMateNavigatorObserver>();
We should be using the `RouteTracker` throughout the codebase, not the observer. We should keep the observer as strictly an external object that will be used in the guest app. 

This way we can make sure it only has the functionality for the guest app and the rest of the things we need we get through the route tracker.

2023-09-28 17:53 UTC, ferrarafer commented on lib/src/widgets/interaction_recorder/interaction_recorder_viewmodel.dart
> +  final _routerObserver = locator<SessionMateNavigatorObserver>();
Yeah, you are right! I don't know why I used the observer and not the tracker. All changes made.

2023-09-28 17:53 UTC, ferrarafer commented on lib/src/app/locator_setup.dart
> +  locator.registerLazySingleton(() => SessionMateNavigatorObserver.instance);
🙈

2023-09-28 17:55 UTC, ferrarafer commented on lib/src/http/event_tracker.dart
> +  final _routerObserver = locator<SessionMateNavigatorObserver>();
I was thinking that could be useful to know if a developer awaits for the response or not. But we can remove it if you want.

2023-09-29 07:19 UTC, FilledStacks approved these changes

2023-09-29 07:19 UTC, merged